### PR TITLE
 Handle GenericXMLElement in FilterUtils.getGeometryValue()

### LINKED ISSUE #1100: IsSurface with XPathExpression fails
Example:
```
 <ogc:Function name="IsSurface">
    <ogc:PropertyName>bu-core2d:geometry2D/bu-base:BuildingGeometry2D/bu-base:geometry</ogc:PropertyName>
</ogc:Function>
```
GetMap does not render the features. Warning in the log: `[07:36:09] WARN: [SymbologyParser?] Evaluating the following expression resulted in an error 'The IsSurface? function's first argument did not evaluate to a geometry.'`

### PR DESCRIPTION
**Pull request by lgoltz**
Fixes #1100

### CODE REVIEW

**Comment by lgoltz** [comment]
Verified by user.

File: deegree-core/deegree-core-base/src/main/java/org/deegree/filter/utils/FilterUtils.java [hunk 1]
```diff
@@ -58,6 +61,14 @@ public static Geometry getGeometryValue( TypedObjectNode node ) {
             geom = (Geometry) node;
         } else if ( node instanceof Property && ( (Property) node ).getValue() instanceof Geometry ) {
             geom = (Geometry) ( (Property) node ).getValue();
+        } else if ( node instanceof GenericXMLElement ) {
+            GenericXMLElement xml = (GenericXMLElement) node;
+            if ( xml.getChildren() != null && !xml.getChildren().isEmpty() ) {
```
Comment (stephanr) [inline deegree-core/deegree-core-base/src/main/java/org/deegree/filter/utils/FilterUtils.java:66]: If GenericXMLElement is a collection type, it would be preferable that the size of the collection is also checked for exactly one element.

**Review by tfr42 — APPROVED** [review]
Approved by TMC
